<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Peppermint.FleetManagement.Application\Peppermint.FleetManagement.Application.csproj" />
    <ProjectReference Include="..\Peppermint.FleetManagement.Infrastructure\Peppermint.FleetManagement.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="robots.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>